const riddles = {
  "A": { // Parking
    "Route A": "CRITICAL: SIGNAL TRACED TO THE SECTOR OF ROLLING GIANTS. FIND THE ARCHWAY WHERE THE RUBBER MEETS THE CONCRETE. THE NEXT DATA PACKET IS HIDDEN AT THE GROUND FLOOR LOBBY.",
    "Route B": "NEMESIS INTERCEPT: PARKING SECTOR BREACHED. SEEK THE LOWEST LEVEL TO FIND THE NEXT UPLINK.",
    "Route C": "ENCRYPTED: TRANSMISSION DETECTED NEAR THE EXHAUST VENTS. PROCEED TO THE PARKING BAYS.",
    "Route D": "SYSTEM ALERT: HARDWARE DETECTED IN THE OPEN AIR STAGING AREA. SEARCH THE PARKING LOT.",
    "Route E": "NODE ALPHA FOUND: THE ROADS END HERE. SCAN THE MARKER NEAR THE PARKING ENTRANCE."
  }
  // B, C, D, E, F will follow this pattern
};